
/*
 *  This file was generated by the SOM Compiler.
 *  Generated using:
 *     SOM incremental update: 2.42
 */

/*
 *  This file was generated by the SOM Compiler and Emitter Framework.
 *  Generated using: 
 *      SOM Emitter emitctm: 2.42
 */

#ifndef SOM_Module_newprn_Source
#define SOM_Module_newprn_Source
#endif
#define NewPrinter_Class_Source

#include "newprn.ih"


SOM_Scope BOOL  SOMLINK newprn_wpModifyPopupMenu(NewPrinter *somSelf, 
                                                 HWND hwndMenu, 
                                                 HWND hwndCnr, 
                                                 ULONG iPosition)
{
    HMODULE module;
    ULONG rc;

    /* NewPrinterData *somThis = NewPrinterGetData(somSelf); */
    NewPrinterMethodDebug("NewPrinter","newprn_wpModifyPopupMenu");

    DosQueryModuleHandle(_somLocateClassFile(SOMClassMgrObject,
                                             SOM_IdFromString("NewPrinter"),
                                             NewPrinter_MajorVersion,
                                             NewPrinter_MinorVersion), &module);

    rc = NewPrinter_parent_WPPrinter_wpModifyPopupMenu(somSelf,
                                                       hwndMenu,
                                                       hwndCnr,
                                                       iPosition);

    if( (SHORT) WinSendMsg(hwndMenu, MM_QUERYITEMATTR, MPFROM2SHORT(WPPOIDM_PD_HOLD, TRUE),
                MPFROMSHORT(MIA_CHECKED))  & MIA_CHECKED)
       _wpInsertPopupMenuItems( somSelf, hwndMenu, 0,
                                module, ID_RELEASE, 0);
    else
    if( (SHORT) WinSendMsg(hwndMenu, MM_QUERYITEMATTR, MPFROM2SHORT(WPPOIDM_PD_RELEASE, TRUE),
                MPFROMSHORT(MIA_CHECKED))  & MIA_CHECKED)

       _wpInsertPopupMenuItems( somSelf, hwndMenu, 0,
                                module, ID_HOLD, 0);


    return rc;

}

SOM_Scope BOOL  SOMLINK newprn_wpMenuItemSelected(NewPrinter *somSelf, 
                                                  HWND hwndFrame, 
                                                  ULONG ulMenuId)
{
    /* NewPrinterData *somThis = NewPrinterGetData(somSelf); */
    NewPrinterMethodDebug("NewPrinter","newprn_wpMenuItemSelected");

    switch(ulMenuId)
    {
       case ID_HOLD:    _wpHoldPrinter(somSelf); return TRUE;
       case ID_RELEASE: _wpReleasePrinter(somSelf); return TRUE;
    }

    return (NewPrinter_parent_WPPrinter_wpMenuItemSelected(somSelf, 
                                                           hwndFrame, 
                                                           ulMenuId));
}
